type: object
additionalProperties:
  type: object
  properties:
    template:
      type: string
      description: The route's template.
    paths:
      type: object
      additionalProperties:
        type: object
        properties:
          page:
            type: string
            description: The page for the path.
          index:
            type: boolean
            description: Determines the index path.
          path:
            type: string
            description: The path.
        description: The path.
  description: The root route of many paths.
